### ISSUE TITLE
Could not find a declaration file for module 'mathkeyboardengine'

### ISSUE THREAD

**Issue by iamelru** [MathKeyboardEngine/MathKeyboardEngine#9]
Hello! Thank you for this great library!
Unfortunately, there is an issue with the declaration files that i cannot seem to override.

![Screenshot 2023-12-29 at 10 29 11](https://github.com/MathKeyboardEngine/MathKeyboardEngine/assets/15969925/f30fb000-855b-416d-9a8e-6f5c81ef797f)

Thank you and Happy new year!

**Comment by SymboLinker** [comment]
Hi!

I am unable to reproduce the problem. Could you help me? :)

I'm using:
- VS Code.
- mathkeyboardengine v1.1.0.
- a file "test.js" or "test.mjs" with my source code and "package.json" that contains the line `"type": "module",`. (For the full test application I just created, see [Test.zip](https://github.com/MathKeyboardEngine/MathKeyboardEngine/files/13797058/Test.zip).)
- no VS Code Extension for additional type checking.

I made sure via
```
npm uninstall -g mathkeyboardengine
npm uninstall mathkeyboardengine
npm install mathkeyboardengine
npm ls
npm ls -g
```
that no other installation of mathkeyboardengine on my computer "fixes" the type declarations for me.

If I change the file extension from ".js" (or ".mjs") to ".ts", I also don't get a syntax analysis error and I can see the types when hovering a method name. When I deliberately mess up the import name, for example "makbengine", then I get an error (but of course not the one you have), so at least some checking is done.

When I hover a method, the types are shown:
![afbeelding](https://github.com/MathKeyboardEngine/MathKeyboardEngine/assets/32139898/dd24a1b9-b4e5-448a-bea6-9a0c984260f9)

I notice that the color of your import statement (blueish)
![afbeelding](https://github.com/MathKeyboardEngine/MathKeyboardEngine/assets/32139898/77078acf-f072-4421-8138-4bb11fe29bb9)
is different from mine (brownish):
![afbeelding](https://github.com/MathKeyboardEngine/MathKeyboardEngine/assets/32139898/33450865-cd92-4253-9aa7-ec2ad27cb5df)

So, at least something is different between our dev environments.

Could you provide more information about your setup?

**Comment by SymboLinker** [comment]
I close this issue after 2 weeks of no response.
